/**:
  ros__parameters:
    use_sim_time: false    # Estamos en vivo, usamos el reloj real de la RPi5
    frequency: 20.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true
    
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # MOTORES
    odom0: /sigyn/wheel_odom
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  false, false,  # Solo confiamos en la velocidad de avance (vx)
                   false, false, true,
                   false, false, false]

    # IMU BNO08X
    imu0: /imu_topic
    imu0_config: [false, false, false,
                  false, false, true,    # Yaw absoluto
                  false, false, false,
                  false, false, true,    # Velocidad Angular Z (vyaw)
                  false, false, false]   # Aceleraciones lineales APAGADAS
    imu0_remove_gravitational_acceleration: false

    # MTF-02P
    odom1: /sensor/odom
    odom1_config: [false, false, false,
                  false, false, false,
                  true,  true,  false,   # vx y vy sí
                  false, false, false,
                  false, false, false]
    #odom1_relative: false  # Normalmente las velocidades son relativas al robot
    #odom1_queue_size: 2
    #odom1_nodelay: false